name: Check PRs

on:
  pull_request_target:
    types:
      - synchronize
      - opened
      
jobs:
  check-prs:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List Open PRs
        id: list-prs
        run: |
          $prs = Invoke-RestMethod -Method Get -Uri "https://api.github.com/repos/${{ github.repository }}/pulls?state=open&base=${{ github.event.pull_request.base.ref }}"
          echo "::set-output name=prs::$prs"

      - name: Check PRs
        run: |
          $prs = ${{ steps.list-prs.outputs.prs }}
          if ($prs -ne $null) {
            Write-Host "There are other open pull requests for this branch:"
            Write-Host "$prs"
            echo "::set-output name=check_status::failure"
          } else {
            Write-Host "No other open pull requests for this branch."
            echo "::set-output name=check_status::success"
          }

      - name: Set Status Check
        run: |
          $status = @{
            owner = $env:GITHUB_REPOSITORY.Split("/")[0]
            repo = $env:GITHUB_REPOSITORY.Split("/")[1]
            sha = $env:GITHUB_SHA
            state = ${{ steps.check-prs.outputs.check_status }}
            context = "Check PRs"
            description = "Check if there are other open pull requests for this branch"
          } | ConvertTo-Json
          Invoke-RestMethod -Method Post -Uri "https://api.github.com/repos/${{ github.repository }}/statuses/$env:GITHUB_SHA" -Headers @{Authorization = "Bearer $env:GITHUB_TOKEN"} -ContentType "application/json" -Body $status
