name: Check PRs

on:
  pull_request_target:
    types:
      - synchronize
      - opened
jobs:
  check-prs:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List Open PRs
        id: list-prs
        run: |
          prs=$(curl -s -X GET "https://api.github.com/repos/${{ github.repository }}/pulls?state=open&base=${{ github.event.pull_request.base.ref }}")
          echo "PRS=$prs" >> $GITHUB_ENV

      - name: Check PRs
        id: check-prs
        run: |
          prs=$PRS
          if [[ ! -z $prs ]]; then
            echo "There are other open pull requests for this branch:"
            echo "$prs"
            echo "::set-env name=CHECK_STATUS::failure"
          else
            echo "No other open pull requests for this branch."
            echo "::set-env name=CHECK_STATUS::success"
          fi

      - name: Set Status Check
        run: |
          status='{
            "owner": "'$GITHUB_REPOSITORY_OWNER'",
            "repo": "'$GITHUB_REPOSITORY'",
            "sha": "'$GITHUB_SHA'",
            "state": "'$CHECK_STATUS'",
            "context": "Check PRs",
            "description": "Check if there are other open pull requests for this branch"
          }'
          curl -s -X POST "https://api.github.com/repos/${{ github.repository }}/statuses/$GITHUB_SHA" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "$status"
