name: Check PRs

on:
  pull_request_target:
    types: [opened, synchronize]
    
jobs:
  check-prs:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List Open PRs
        id: list-prs
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            $pullRequests = Invoke-RestMethod -Method Get -Uri "https://api.github.com/repos/$(echo $GITHUB_REPOSITORY)/pulls?state=open&base=$(echo ${{ github.event.pull_request.base.ref }})"
            $pullRequests

      - name: Check PRs
        run: |
          $prs = ${{ steps.list-prs.outputs.result }} | ConvertFrom-Json
          if ($prs -ne $null) {
            Write-Host "There are other open pull requests for this branch:"
            Write-Host "$prs"
            echo "::set-output name=check_status::failure"
          } else {
            Write-Host "No other open pull requests for this branch."
            echo "::set-output name=check_status::success"
          }

      - name: Set Status Check
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const status = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.pull_request.head.sha,
              state: '${{ steps.check-prs.outputs.check_status }}',
              context: 'Check PRs',
              description: 'Check if there are other open pull requests for this branch',
            };
            await github.repos.createCommitStatus(status);
