name: Check PRs

on:
  pull_request_target:
    types:
      - synchronize
      - opened
      
jobs:
  check-prs:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List Open PRs
        id: list-prs
        run: |
          prs=$(curl -s -X GET \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?state=open&base=${{ github.event.pull_request.base.ref }}")
          echo "::set-output name=prs::$prs"

      - name: Check PRs
        run: |
          prs=$(echo "${{ steps.list-prs.outputs.prs }}" | jq '.[] | select(.number != ${{ github.event.pull_request.number }})')
          if [ ! -z "$prs" ]; then
            echo "There are other open pull requests for this branch:"
            echo "$prs"
            echo "::set-output name=check_status::failure"
          else
            echo "No other open pull requests for this branch."
            echo "::set-output name=check_status::success"
          fi

      - name: Set Status Check
        run: |
          token=$(curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }}" \
            -d "{
              \"state\": \"${{ steps.check-prs.outputs.check_status }}\",
              \"context\": \"Check PRs\",
              \"description\": \"Check if there are other open pull requests for this branch\"
            }")
