name: Restrict Merge

on:
  pull_request:
    types:
      - synchronize
      - opened

jobs:
  check-prs:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List Open PRs
        id: list-prs
        run: |
          $prs = Invoke-RestMethod -Method Get -Uri "https://api.github.com/repos/${{ github.repository }}/pulls?state=open&base=${{ github.event.pull_request.base.ref }}"
          $prs | ConvertTo-Json | Out-File prs.json
           foreach ($pr in $prs) {
            echo "PR Number: $($pr.number)"
          }
          echo "PR_LIST = ${{ env.PR_LIST }}"
      - name: Check PRs
        run: |
          $prs = Get-Content prs.json | ConvertFrom-Json
          if ($prs -ne $null) {
            $oldestPR = $prs | Sort-Object -Property created_at | Select-Object -First 1
            echo "oldestPR.number: $oldestPR.number"
            echo "GITHUB_PR_NUMBER: $env:GITHUB_PR_NUMBER"
            if ($oldestPR.number -ne $env:GITHUB_PR_NUMBER ) {
              $status = @{
                check_status = "failure"
                message = "There are other open pull requests for this branch."
              } | ConvertTo-Json | Out-File check_status.json
              echo "There are other open pull requests for this branch:"
              foreach ($pr in $prs) {
                echo "PR Number: $($pr.number)"
                echo $pr
              }
            }
            else {
              $status = @{
                check_status = "success"
                message = "No other open pull requests for this branch."
              } | ConvertTo-Json | Out-File check_status.json
              echo "No other open pull requests for this branch."
            }
          }
          else {
            $status = @{
              check_status = "success"
              message = "No other open pull requests for this branch."
            } | ConvertTo-Json | Out-File check_status.json
            echo "No other open pull requests for this branch."
          }

      - name: Set Status Check
        run: |
          $status = Get-Content check_status.json | ConvertFrom-Json
          echo "check_status = $($status.check_status)"
          echo "message = $($status.message)"

          $statusData = @{
            owner = $env:GITHUB_REPOSITORY.Split("/")[0]
            repo = $env:GITHUB_REPOSITORY.Split("/")[1]
            sha = $env:GITHUB_SHA
            state = $status.check_status
            context = "check-prsRM"
            description = $status.message
          }

          $token = '${{ secrets.TOKEN_SECRET }}'
          $header = @{
            Authorization = "Bearer $token"
            "Content-Type" = "application/json"
          }

          $apiUrl = "https://api.github.com/repos/$($env:GITHUB_REPOSITORY)/statuses/$($env:GITHUB_SHA)"

          Invoke-RestMethod -Method Post -Uri $apiUrl -Headers $header -ContentType "application/json" -Body ($statusData | ConvertTo-Json)
